site_name: Smart Citizen Docs
site_description: Smart Citizen Documentation
site_author: Smart Citizen Team
site_url: https://docs.smartcitizen.me/
repo_name: smartcitizen-docs
repo_url: https://github.com/fablabbcn/smartcitizen-docs
# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

nav:
  - Main:
    - Welcome: index.md
    - Hardware:
      - Hardware Ecosystem: Components/index.md
      - Smart Citizen Kit:
        - What is it?: Smart Citizen Kit.md
        - Components:
          - Data Board: Components/boards/Data Board.md
          - Urban Board: Components/boards/Urban Board.md
        - Enclosures: Components/enclosures/Enclosures.md
      - Smart Citizen Station:
        - What is it?: Smart Citizen Station.md
        - Components:
          - Gas Pro Sensor Board: Components/boards/Gases Pro Board.md
          - PM Board: Components/boards/PM Board.md
          - Analog Sensor Board: Components/boards/Analog Sensor Board.md
      - Soil and Water: Components/Soil and water.md
      - Supported sensors: Components/Auxiliary Connector.md
      - Power Supply: Components/boards/Power Supply.md
    - Firmware: Components/Firmware.md
    - Sensor Knowledge:
      - Air:
        - Particulate Matter: Components/sensors/air/PM Sensors.md
        - Noise: Components/sensors/air/Noise.md
        - Metal Oxide Sensors:
          - What to expect: Components/sensors/air/Metal Oxide.md
          - eCO2/TVOC: Components/sensors/air/CCS811.md
        - Electrochemical Sensors: Components/sensors/air/Electrochemical Sensors.md
        # - Air Mobile sensors: Components/sensors/air/mobile.md
      - Soil and Water:
        - Soil Moisture Sensors: Components/sensors/soil/Soil Moisture Sensors.md
        - Tensionmenter: Components/sensors/soil/Tensiometer.md
        # - Water Mobile Sensors: Components/sensors/water/mobile.md
    - FAQ: _FAQ.md
    - Troubleshooting: Troubleshooting.md    
  - Data:
    - Sensor Platform: Data/Sensor Platform.md
    - Smart Citizen API: Data/Smart Citizen API.md
    - Data Analysis: Data/Data Analysis.md
  - Use cases:
    - Main: Use cases/index.md
    - Citizen Sensing Toolkit: Use cases/Citizen Sensing Toolkit.md
    - Research Projects: Use cases/Research.md
    - Additional material: Use cases/Presentations.md
    - Friend projects: Use cases/Friends.md
  - Guides:
    - Main: Guides/index.md
    - Getting started:
      - Onboarding Sensors: Guides/getting started/Onboarding Sensors.md
      - Downloading platform data: Guides/getting started/Downloading the Data.md
      - Uploading SD-card data: Guides/getting started/Uploading SD Card Data.md
      - Updating the Wi-Fi: Guides/getting started/Updating the Wi-Fi.md
      - Using the Shell: Guides/getting started/Using the Shell.md
    - Firmware:
      - Update the firmware: Guides/firmware/Update the firmware.md
      - Edit the firmware: Guides/firmware/Edit the Firmware.md
      - Debug the firmware: Guides/firmware/Debug the firmware.md
    - Data Analysis:
      - Framework Installation: Guides/data/Install the framework.md
      - Make reports of your data: Guides/data/Make reports of your data.md
      - Creating interfaces: Guides/data/Creating Interfaces.md
      - Organise your data: Guides/data/Organise your data.md
      - Handling calibration data: Guides/data/Handling calibration data.md
      - Custom data processing: Guides/data/Custom data processing.md
      # - Model your sensor data: Guides/Creating Models for Sensors Calibration.md
      # - Analyse your data in batch: Guides/Analyse your data in batch.md
      - Uploading data to zenodo: Guides/data/Upload data to zenodo.md
    - Deploying sensors: 
      - Smart Citizen Kit: Guides/deployments/Deploying SCK.md
      - iSCAPE Station V1: Guides/deployments/Deploying iSCAPE Station V1.md
      - iSCAPE Station V2: Guides/deployments/Deploying iSCAPE Station V2.md
      - Smart Citizen Station V3: Guides/deployments/Deploying Smart Citizen Station.md
      - Smart Citizen Connectivity Units: Guides/deployments/Installing Connectivity Units.md
      - Smart Citizen Soil and water sensors: Guides/deployments/Soil and water sensors.md
      - Almabike sensors: Guides/deployments/Almabike sensors.md
      - Smart Citizen Power Supply: Guides/deployments/Using the power supply.md
    - Enclosures:
      - Making your own enclosures: Guides/enclosures/Making your own enclosures.md
    - Legacy Hardware:
      - Smart Citizen 1.1:
        - Main: Components/legacy/index.md
        - Hardware: Components/legacy/Hardware.md
        - Command Line: Components/legacy/Command Line.md
        - FAQ: Components/legacy/Faq.md
        - Troubleshooting: Components/legacy/Troubleshooting.md
      - Smart Citizen 2.0:
        - Main: Components/legacy/sck.md
        - About the CO-NO2 MOs: Components/sensors/air/SGX MICS.md

theme:
  name: 'material'
  features:
    - instant
    - navigation.expand
    - tabs
  custom_dir: 'custom_theme'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true
  icon:
    repo: fontawesome/brands/git-alt

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/smartcitizenkit'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/smartcitizenkit/'
    - icon: fontawesome/brands/github
      link: 'https://www.instagram.com/smartcitizenkit/'
  project: 'The Smart Citizen as part of the iSCAPE project has received funding from the European Communityâ€™s H2020 Programme under Grant Agreement No. 689954.'
  footer_logo: '/assets/images/eu-flag.png'
  license: 'CC Attribution-NonCommercial-ShareAlike 4.0 International'

# plugins:
#     - with-pdf:
#         author: Smart Citizen
#         copyright: 'CC Attribution-NonCommercial-ShareAlike 4.0 International'
#         cover: true
#         cover_title: Smart Citizen Sensors Documentation
#         cover_subtitle: Smart Citizen - Oct 2020
#         toc_title: Table of contents
#         heading_shift: false
#         toc_level: 3
#         ordered_chapter_level: 2
#         excludes_children:
#            - 'release-notes/:upgrading'
#            - 'release-notes/:changelog'
#         exclude_pages:
#            - 'Components/'
#            - 'Guides/'
#            - 'Legacy Hardware/'
#            - 'Sensors Analysis Framework/'
#            - 'Sensor Platform/'
#         convert_iframe:
#            - src: IFRAME SRC
#              img: POSTER IMAGE URL
#              text: ALTERNATE TEXT
#            - src: ...
#         two_columns_level: 3
#         render_js: true
#         headless_chrome_path: headless-chromium
#         output_path: ..
#         enabled_if_env: ENABLE_PDF_EXPORT
#         debug_html: true
#         show_anchors: true
#         verbose: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'