site_name: Smart Citizen Docs
site_description: Smart Citizen Documentation
site_author: Smart Citizen Team
site_url: https://docs.smartcitizen.me/

# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

# pages:
#   -  Home: index.md

# nav:
#     - Home: index.md

theme:
  name: 'material'
  custom_dir: 'custom_theme'
  palette:
    primary: 'blue'
    #primary: 'indigo'
    accent: 'yelllow'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/smartcitizenkit'
    - type: 'facebook'
      link: 'https://www.facebook.com/smartcitizenBCN/'
  project: 'The Smart Citizen has received funding from the European Communityâ€™s H2020 Programme under Grant Agreement No. 689954.'
  footer_logo: '/assets/images/eu-flag.png'
  license: ''
  repo_name: smartcitizen-docs
  repo_url: https://github.com/fablabbcn/smartcitizen-docs

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: Link
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'